<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/google_ads/localization/de_CH.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/21/2012 18:03:42
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['ads_error'] = 'Sie können sich nur anmelden, wenn Adblock (Plus) ausgeschaltet ist.';

?>