<?php

/*
 +-----------------------------------------------------------------------+
 | ./plugins/google_ads/localization/en_GB.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: myroundcube@mail4us.net - 03/20/2012 09:32:59
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['ads_error'] = 'Please disable Adblock (Plus) to view this site.';

?>