<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/google_ads/localization/es_ES.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: Yoni - 04/03/2012 06:24:13
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['ads_error'] = 'Por favor, desactivar Adblock (Plus) para acceder a este sitio.';

?>