<?php
/*
 +-----------------------------------------------------------------------+
 | ./plugins/google_ads/localization/fr_FR.inc
 |
 | Language file of MyRoundcube Plugins Bundle
 | Copyright (C) 2010-2012, Roland 'rosali' Liebl
 | Licensed under the GNU GPL
 |
 +-----------------------------------------------------------------------+
 | Author: hugues@mail4us.net - 03/31/2012 15:42:06
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['ads_error'] = 'Merci de désactiver Adblock (plus) pour visionner ce site.';

?>